packages
```{r}
library(tidyverse)
library(dplyr)
library(readr)
library(sf)
library(raster)
library(spData)
library(spDataLarge)
library(tmap) 
library(leaflet) 
library(ggplot2) 
```
data initialization
```{r}
LIHTCPUB <- read_csv("LIHTCPUB.CSV")
dat <- LIHTCPUB
remove(LIHTCPUB)
```
filtering 
```{r}
#Filters to only Tennessee
nashdat <- dat %>%
  filter(proj_st=="TN")

#Filters to only Nashville data
nashdat <- nashdat %>%
  filter(proj_cty=="NASHVILLE")
  
  #Dropped NA for Project Addresses
nashdat <- nashdat%>%
  drop_na(proj_add)
#Dropped NA for Project Zipcodes
nashdat <- nashdat%>%
  drop_na(proj_zip)
#Filtered out the data points without years
nashdat <- nashdat%>%
  filter(yr_pis!= 9999 & yr_pis!= 8888)
```
initial map creation
```{r}
NashvilleZipMap <- leaflet(nashdat) %>%
  addTiles() %>%
  addMarkers(lng=~longitude, 
             lat=~latitude,
             popup=~paste0("Project Address: ",
                           proj_add, 
                           "<br/>ZIP: ",
                           proj_zip, 
                           "<br/>Annual dollar amount of tax credits allocated: ",
                           allocamt, 
                           "<br/>Total Number of Units: ",
                           n_units))
NashvilleZipMap
```
sorting data into groups
```{r}
#creating categories for variables 
nashdat <- nashdat %>%
  mutate(n_units_sorted = case_when((n_units <= 10) ~ 'Group1',
                                     (n_units >= 11 & n_units <= 50) ~ 'Group2',
                                     (n_units >= 51 & n_units < 100) ~ 'Group3',
                                     (n_units > 101) ~ 'Group4',
                                     )
  )
```
